default_platform(:android)

platform :android do
  desc "Submit to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleDebug")
    crashlytics(
      emails: "<testers>",
      api_token: "<fabric_api_key>",
      build_secret: "<fabric_api_secret>"
    )
  end

  desc "Build release APK"
  lane :build do
        gradle(task: "clean assembleRelease")
  end

  desc "Release to Google Play[Build,Screenshots,Deploy]"
  lane :release do
      build
      screenshots
      deploy
  end

  desc "Release without screenshots"
  lane :release_no_screenshot do
    deploy
  end

  desc "Capture screenshots. Please run emulator before run"
  lane :screenshots do
    gradle(task: "clean")
    build_android_app(
      task: 'assemble',
      build_type: 'Debug'
    )
    build_android_app(
      task: 'assemble',
      build_type: 'AndroidTest'
    )
    capture_android_screenshots(
      locales: [<languages>],
      clear_previous_screenshots: true,
      launch_arguments:[<screenshots_array>],
      app_apk_path: "app/build/outputs/apk/debug/app-debug.apk",
      tests_apk_path: "app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk"
    )
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end

  

end
