# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Build release IPA"
  lane :build do
    automatic_code_signing(
      path: "<project_name>.xcodeproj",
      use_automatic_signing: true,
      team_id: "<team_id>",
      targets: ["<project_name>"]
    )
    build_app(scheme: "<project_name>",workspace: "<project_name>.xcworkspace",include_bitcode: true,export_xcargs: "-allowProvisioningUpdates")
  end

  desc "Release to Apple Store[Build,Screenshots,Deploy]"
  lane :release do
      build
      screenshots
      deploy
  end

  desc "Release without screenshots"
  lane :release_no_screenshot do
      build
      deploy
  end

  desc "Capture screenshots"
  lane :screenshots do
    capture_screenshots(
      skip_open_summary: true,
      number_of_retries: 1,
      reinstall_app: true
    )
  end

  desc "Deploy a new version to the Apple Store"
  lane :deploy do
      deliver(
        ignore_language_directory_validation: true,
   	  	force:true,
   	  	overwrite_screenshots:true
      )
  end
end
